name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - uses: alexr03/jenkinsremotebuilder@master
        env:
          JENKINS_HOST: http://build.tcadmin.com:8080
          JENKINS_USER: Alex
          JENKINS_API_KEY: ${{ secrets.JENKINS_API_KEY }}
          JOB: /Alexr03%20Modules/job/Ban%20Management
          DOWNLOAD_ARTIFACT: true
          ARTIFACT_NAME: output.zip
          WAIT_FOR_COMPLETION: true
      - uses: alexr03/ips-resource-updater@master
        with:
          ips_url: https://community.tcadmin.com
          api_key: ${{ secrets.IPS_API_KEY }}
          resource_id: 81
          file_name: 'test.jpg'
          file_url: 'https://www.gamasutra.com/db_area/images/news/2018/Jun/320213/supermario64thumb1.jpg'
          version: '1.0.2'
          changelog: ''
          save_previous: true
