name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    - name: Restore dependencies
      run: nuget restore -PackagesDirectory ../packages 
    - name: Build
      run: msbuild TCAdminCustomMods.csproj /p:Configuration=Debug
    - uses: alexr03/tcadmin-module-packager-action@v1
      name: Package TCAdmin Module
